### ISSUE TITLE
Need to finish porting all data from savbook to savmaps

### ISSUE THREAD

**Issue by carlvlewis** [opensavannah/savmaps#5]
Before we get too bogged down in the mud with submission forms and security concerns, could @egomadking lead the way in being the gatekeeper of the current workbook? 

There's still a . **lot** of data from SavBook that hasn't been brought into SavMaps in any fashion, staging or otherwise. We can figure out the submission part better later. But let's get in there what we have available now.

I'll help some but it needs to be coordinated.

**Comment by royemosby** [comment]
I'll have the data from [SavBooks](https://docs.google.com/spreadsheets/d/1aEeWwd_DN5csN5Wb-LafN9GPu3my4xd-tGiy3C7lLu8/edit#gid=1638719828) over by tomorrow evening. I will need some assistance if we are going to use import.io or artoo to go through some of the online resources.

**Comment by carlvlewis** [comment]
Excellent! It looks so much more complete now. DId you need help with import.io or artoo or scraper of choice?

**Comment by royemosby** [comment]
[United Way's 211](http://www.referweb.net/uwce/), surprise surprise, has a terms of service that disallow that. In addition to that, they have a bit over 900 categories where the info is behind queries. I was going to look for other sources Sun/Mon. I have a project due tomorrow and needs my attention.

**Comment by carlvlewis** [comment]
Honestly, I would scrape it from UW anyway. The data doesn't belong to them. It's in the public domain.

**Comment by carlvlewis** [comment]
And I think you mean refernet's ToS. They are simply a middleman.
