### ISSUE TITLE
Display of non-physical resources

### ISSUE THREAD

**Issue by royemosby** [opensavannah/savmaps#7]
How do we include hotlines and other non-physical resources in a visual resource directory?

[Rape Crisis Center ](https://www.rccsav.org), for example.

**Comment by carlvlewis** [comment]
Hmmm… I don’t know if we need to.

**Comment by royemosby** [comment]
That would leave hotlines such as rape, crisis, suicide unrepresented. I don't see that as being in the spirit of the project as these are resources just as important as those who offer physical services. I don't think that this question needs to be answered immediately...

**Comment by carlvlewis** [comment]
No but it's important! For SavMaps, it's not really relevant but for SavBook and ohana it is.

**Comment by carlvlewis** [comment]
Wait, @egomadking , it just hit me: Do you have edit access yourself to the source workbook? I know I locked the sheets, but not sure if I gave you edit permissions.

**Comment by royemosby** [comment]
@carlvlewis I can make changes to that spreadsheet. I have some bad coordinate info before I move the content over.

**Comment by carlvlewis** [comment]
Okay, cool, gotcha. I'm gradually adding in images to the image column.

**Comment by royemosby** [comment]
Closing issue and adding to "Content strategy" project
