### ISSUE TITLE
Fixing colors of markers to correspond to legend

### ISSUE THREAD

**Issue by carlvlewis** [opensavannah/savmaps#8]
So it looks like @egomadking presumably made a best effort attempt to solve this by categorizing the entries' colors with the corresponding hex code values for the legend...

... problem is, the code can't read hex values (insane, I know, right?). Instead, it uses the following list of colors, because they're best suited for colorblind-friendliness:
![](http://cvlassets.s3.amazonaws.com/Screenshot%202017-09-02%2023.44.40.png)

So, I've sorted the entries alphabetically A-Z, and am changing the hex code values out for the closest one I can find in the legend.

**Comment by carlvlewis** [comment]
Alternatively, would it be better if we changed it in the actual JS for the colors to match the distinct color list provided in `readme.md`? Looking now to see if I can find where the RGB or hex values of that color scheme is being defined with those titles.

**Comment by royemosby** [comment]
@carlvlewis I see now that the constraint lives in how it presents the marker. All the markers live in one of 2 PNG files based on screen resolution- `scripts/Leaflet.awesome-markers/dist/images/markers-soft.png` or `markers-soft@2x.png`. 

`scripts/Leaflet.awesome-markers/dist/leaflet.awesome-markers.css` is used to position that file so the appropriate marker shows. The color names are a part of a class-builder somewhere.

**Comment by royemosby** [comment]
Color change completed. Other color scheme going onto the back-burner for future consideration.

**Comment by carlvlewis** [comment]
Sweeeet. Nice work, Roy.

**Comment by carlvlewis** [comment]
Aha! Good catch. Yes, it looks like it’s just using the .png as a single
source to make the script as lightweight as possible. We can, if you want,
then, always change those colors to reflect the color scheme you devised
originally.

Is the old color scheme part of the Open Eligibility protocol, or was it a
scheme you devised yourself of visually distinct colors? If it’s one you
devised yourself, I don’t see the need to do the extra work and change this
here. If it’s part of a standard, then maybe we should prioritize it.
